name: Push pipeline on OpenHEXA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test Custom Action
        uses: blsq/openhexa-push-pilelin-action@v1
        with:
          - token: ${{ secrets.OH_TOKEN }}
          - workspace: openhexa-push-pipeline-action-example
          - pipeline: example