name: Push pipeline on OpenHEXA

on:
  push:
    branches:
      - main

jobs:
  push-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Push pipeline on OpenHEXA
        uses: blsq/openhexa-push-pipeline-action@v1.0.0
        with:
          token: ${{ secrets.OH_TOKEN }}
          workspace: openhexa-push-pipeline-action-example
          pipeline: example